import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}><div className="lg:bg-[#F0F2F5] w-full h-10 place-content-center lg:px-12 pl-4 font-inter text-sm text-[#BDBDBD] shadow-[0px_1px_0px_0px_#D9D9D9]">LOGO</div>{children}</body>
    </html>
  );
}
